Add missing local auth DB functions to fix login TypeError
Fixes login failing with "[Local Auth] Login failed TypeError: (void 0) is not a function".

localAuth.ts calls db functions that were never implemented. Added:
- getUserByEmail
- getLocalAuthCredentialByEmail
- getLocalAuthCredentialByOpenId
- createLocalAuthCredential
- updateLocalAuthCredential

Signed-off-by: jcheng510 <jade@superhumn.co>